name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  pathogen-ci:
    strategy:
      matrix:
        runtime: [docker, conda]
    permissions:
      id-token: write
    uses: nextstrain/.github/.github/workflows/pathogen-repo-build.yaml@trs/pathogen-repo-build/wait-for-aws-batch-job
    secrets: inherit
    with:
      runtime: ${{ matrix.runtime }}
      run: |
        nextstrain build \
          phylogenetic \
          --configfile profiles/ci/builds.yaml
      artifact-name: output-${{ matrix.runtime }}
      artifact-paths: |
        phylogenetic/auspice/
        phylogenetic/results/
        phylogenetic/benchmarks/
        phylogenetic/logs/
        phylogenetic/.snakemake/log/
